# Generated by Django 3.0.6 on 2020-05-17 21:41

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200517_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/'),
        ),
    ]
