# Generated by Django 3.0.6 on 2020-05-17 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200517_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 22, 50, 39, 261794)),
        ),
    ]
